# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - master
    exclude:
    - issue-206

pool:
  vmImage: 'windows-latest'

variables:
- group: Developer-Automation
- name: 'solution'
  value: '**/*.sln'
- name: 'buildPlatform'
  value: 'Any CPU'
- name: 'buildConfiguration'
  value: 'Release'

steps:    
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--no-build'
  env:
    GraphClient__ClientSecret: $(System.AccessToken)
    AwsFacade__SecretKey: $(AwsFacade__SecretKey)
    AdoClient__ClientSecret: $(System.AccessToken)

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0' 
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    publishVstsFeed: '8f93db05-d907-48d6-8537-c2b31e220950'

- task: Bash@3
  inputs:
    targetType: inline
    script: 
        curl -X POST \
        -u :$(System.AccessToken) https://dev.azure.com/{OrganizationName}/{ProjectName}/_apis/build/builds/$(build.buildid)/tags?api-version=6.0 \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d ' ["3982dbbb-9064-4f26-88f7-df7eeeafbd33"]'