# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:    
- task: NuGetToolInstaller@1
  displayName: 'Installing NuGet tools'

- task: DotNetCoreCLI@2
  displayName: 'Restore solution dependencies'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build source code'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet packages'
  inputs:
    command: 'pack --version-suffix $(Build.BuildNumber) --include-symbols'

- task: NuGetCommand@2
  displayName: 'Push NuGet packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '8f93db05-d907-48d6-8537-c2b31e220950'